In [30]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [31]:
# write your code here ^_^
x = np.ones(4)
x

array([1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [32]:
# write your code here ^_^
y = np.zeros(4)
y

array([0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [33]:
# write your code here ^_^
a = x + y
a

array([1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [34]:
# write your code here ^_^
x.ndim

1

In [35]:
x.shape

(4,)

In [36]:
x.size

4

In [37]:
type(x)

numpy.ndarray

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [38]:
# write your code here ^_^
w = np.array([[11, 13, 15],[12, 14, 16]])
w

array([[11, 13, 15],
       [12, 14, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [39]:
# write your code here ^_^
z = np.array([1, 2, 3])
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [63]:
w = w.reshape(6)
w

array([11, 13, 15, 12, 14, 16])

In [65]:
# write your code here ^_^
newArray = np.hstack((w, z))
newArray

array([11, 13, 15, 12, 14, 16,  1,  2,  3])

## Q#8: Print all elements of "newArray" using the loop.

In [70]:
# write your code here ^_^
for i in newArray:
    print(i)

11
13
15
12
14
16
1
2
3


## Q#9: Reverse the columns and rows of "newArray".

In [71]:
# write your code here ^_^
newArray_rev = np.flip(newArray)
newArray_rev

array([ 3,  2,  1, 16, 14, 12, 15, 13, 11])

## Q#10: Decrement all elements of "newArray" with 1.

In [72]:
# write your code here ^_^
newArray -= 1
newArray

array([10, 12, 14, 11, 13, 15,  0,  1,  2])

## Q#11: Find smallest and biggest values in "newArray".

In [74]:
# write your code here ^_^
newArray.min()

0

In [75]:
newArray.max()

15

## Q#12: Print the first row of "newArray" using indexing.

In [77]:
# write your code here ^_^
(newArray[0])

10

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [78]:
# write your code here ^_^
(newArray[1])

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [100]:
# write your code here ^_^
(newArray[4:7:2])

array([13,  0])

## Q#15: Change the shape of "newArray" to (9,1).

In [107]:
# write your code here ^_^
newArray.reshape(9,1)

array([[10],
       [12],
       [14],
       [11],
       [13],
       [15],
       [ 0],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [109]:
# write your code here ^_^
newArray.reshape(3,3)

array([[10, 12, 14],
       [11, 13, 15],
       [ 0,  1,  2]])

# Well Done 🎉