# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
# write your code here ^_^
a = np.linspace(0, 10, 15)
a

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [17]:
# write your code here ^_^
arr1 = np.array([1.1, 2.1, 3.1])
arr2 = np.array([4.1, 5.1, 6.1])
arr3 = np.array([7.1, 8.1, 9.1])
arr4 = np.array([10.1, 11.1, 12.2])
arr_3d = np.array([[[arr1[0], arr1[1], arr1[2]], [arr2[0], arr2[1], arr2[2]]],
                     [[arr3[0], arr3[1], arr3[2]], [arr4[0], arr4[1], arr4[2]]]])

print(arr_3d)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.2]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [18]:
# write your code here ^_^
type(arr_3d)

numpy.ndarray

In [8]:
arr_3d.dtype

dtype('float64')

In [9]:
arr_3d.shape

(2, 2, 3)

In [10]:
arr_3d.size

12

In [11]:
arr_3d.ndim

3

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [19]:
# write your code here ^_^
arr_4d = arr_3d.reshape((1, arr_3d.shape[0], arr_3d.shape[1], arr_3d.shape[2]))
arr_4d.ndim

4

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [33]:
# write your code here ^_^
arr_int = arr_4d.astype(int)
arr_int

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [21]:
# write your code here ^_^
for b in np.nditer(arr_int):
    print(b)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [36]:
arr_int

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

In [41]:
# write your code here ^_^
arr_int[0][1][0][1]

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [45]:
# write your code here ^_^
arr_int[0][0][1][1:3]

array([5, 6])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [50]:
# write your code here ^_^ 
d = np.where(arr_int == 8)
d

(array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [51]:
# write your code here ^_^
arr_int.reshape(2, 3 ,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [60]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

r = np.concatenate((arr1, arr2))
r

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [61]:
# write your code here ^_^
r = np.concatenate((arr1, arr2), axis=1)
r

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [71]:
# write your code here ^_^
arr = np.concatenate((arr1, arr2))
r1, r2 = np.hsplit(arr, 2)
r1
r2

array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')